### ISSUE TITLE
Here are some friendly suggestions

### ISSUE THREAD

**Issue by fate-lovely** [dingdingbai/you-dont-know-js-review#1]
- I have looked all your repos, and noticed that their names are all lowercase, hyphen connected. So I think maybe this one should be renamed to `you-dont-know-js-review`.
- There is a top level directory `You-Dont-Know-JS-review` in your repo, I think it is unnecessary.

**Comment by dingdingbai** [comment]
Thank you for your suggestion. I'll have a look and change it.
